name: Release

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=CURRENT_TAG::${GITHUB_REF/refs\/tags\//}
    - name: print current tag
      run: echo ${{ steps.get_version.outputs.CURRENT_TAG }}
    - uses: actions/checkout@v1
    - name: Runs only if git tag exists
      if: steps.get_version.outputs.CURRENT_TAG != ''
      run: |
        cd release
        ./bumpSemanticVersion.sh ${{ steps.get_version.outputs.CURRENT_TAG }}
